spring:
  config:
    activate:
      on-profile: sun

  sql:
    init:
      mode: never
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fourth_apple_dev
    username: root
    password: 1234

  jpa:
     hibernate:
       ddl-auto: update

     properties:
       hibernate:
         format_sql: true
     defer-datasource-initialization: false